---
- include_role:
    name: rhsso
  when: deploy_rhsso
- include_role:
    name: gitea
  when: deploy_gitea
- include_role:
    name: argocd
  when: deploy_argocd
- include_role:
    name: sonarqube
  when: deploy_sonarqube
- include_role:
    name: nexus
  when: deploy_nexus
- include_role:
    name: legacy-jenkins
  when: deploy_legacy_jenkins
- include_role:
    name: quay
  when: deploy_quay
- include_role:
    name: mattermost
  when: deploy_mattermost_operator
- include_role:
    name: codeready-workspaces
  when: deploy_crw
- include_role:
    name: selenium-grid
  when: deploy_selenium_grid
